### ISSUE TITLE
Question : How to parse a JSON string

### ISSUE THREAD

**Issue by MangelMaxime** [mausch/Fleece#16]
Hi @mausch,

I just discovered Fleece and really appreciate it.
My problem is I have a File so a string representation of Json and I would like to instantiate a type from it.

Here is the code:

```fsharp

type ConfigJson = {
    RelativeRoot: string
}

type ConfigJson with 
    static member Create relativeRoot = { ConfigJson.RelativeRoot = relativeRoot }
    
    static member FromJson(_:ConfigJson) = 
        function
        | JObject o -> ConfigJson.Create <!> (o .@ "relativeRoot")
        | x -> Failure (sprintf "Expected ConfigJson, found %A" x)
        
type Config private () =
    let mutable RelativeRoot = ""
    
    let mutable json = nullArg
    
    
    
    do
        let data = parseJSON(System.IO.File.ReadAllText("server.json"))
        (*ConfigJson.FromJson(data)*)(* Here is the problem *)
        |> ignore
        
    static let instance = Config()

```

I was supposing that FromJson was a method to instantiate the Type but I can't find how to use it. Sure it doesn't take a string as a entry. Could you help me please.

PS: Sorry, if the question is a little dumb.

**Comment by mausch** [comment]
Hi! No question is dumb.

`parseJSON` does take a string as parameter, but it returns a `Choice<'a, string>`. 
If it's Choice1Of2 then the parsing was successful and you have the parsed value. 
If it's Choice2Of2 then there was some parsing error and you get the error message as a string, which you can use to throw as an exception, display to the user or whatever you like.

Does that make sense?

To create a "singleton" instance of Config I recommend using [F#'s lazy expressions](https://msdn.microsoft.com/en-us/library/dd233247(v=vs.110).aspx)

Cheers

**Comment by MangelMaxime** [comment]
Thanks for the answer and the tips.

I think I understand an then if the result is successful then I can pass it to FromJson of ConfigJson ?

**Comment by mausch** [comment]
No, FromJson is called implicitly by parseJSON, you don't need to call it
in your code.

**Comment by MangelMaxime** [comment]
Ok :) Thanks for the help.

I am letting here my problem solved.

```fsharp
namespace Server

open System
open Fleece
open Fleece.Operators
open FSharpPlus

type ConfigJson = {
    RelativeRoot: string
    Server: string
    Database: string
    Uid: string
    Pwd: string
}

type ConfigJson with 
    static member Create relativeRoot server database uid pwd= 
        { 
            ConfigJson.RelativeRoot = relativeRoot;
            ConfigJson.Server = server;
            ConfigJson.Database = database;
            ConfigJson.Uid = uid;
            ConfigJson.Pwd = pwd;
        }
    
    static member FromJSON (_:ConfigJson) = 
        function
        | JObject o -> ConfigJson.Create <!> (o .@ "relativeRoot") <*> (o .@ "server") <*> (o .@ "database") <*> (o .@ "uid") <*> (o .@ "pwd")
        | x -> Failure (sprintf "Expected ConfigJson, found %A" x)

module Config =

    let config: ConfigJson =
        let data: ConfigJson ParseResult = parseJSON(System.IO.File.ReadAllText("server.json"))
        
        match data with
        | Success a -> a
        | Failure e -> failwith "Error when parsing json file"

```
