### ISSUE TITLE
Review naming conventions

### ISSUE THREAD

**Issue by gusty** [mausch/Fleece#22]
I think this project started with original Aeson names, which at the same time are Haskell-ish names.

I propose we use instead more F#ish names, which means that instead of ``fromJSON`` we should use ``ofJSON``.

This can be implemented without breaking changes, by adding another default overload, or by renaming the recently added default for ``FromJSON`` with a clean signature, since it wasn't released yet.

**Comment by wallymathieu** [comment]
Sounds good!

**Comment by wallymathieu** [comment]
Naming of 'JSON' should probably be 'Json': 
https://msdn.microsoft.com/en-us/library/ms229043%28v=vs.100%29.aspx?f=255&MSPPError=-2147217396
Since it's conceptually a f# module function, I think it makes to have the first letter lowercase, i.e. `ofJson` and not `OfJson` as can be seen in [the docs](http://fsharp.org/specs/component-design-guidelines/) about naming.

**Comment by gusty** [comment]
So then we can do the following:

 - rename our recent addition (clean signature default) to ``ofJson``
 - add a default for ``toJson``
 - deprecate generic functions ``fromJSON`` and ``toJSON``
 - add ``ofJson`` and ``toJson`` generic functions

**Comment by wallymathieu** [comment]
So I guess that the static members used to implement Json serialization should be with a capital first letter?

**Comment by gusty** [comment]
Thanks, I fixed my previous comment.

**Comment by wallymathieu** [comment]
It's kind of weird to have `Person.Create` instead of `Person.create` since you might want to use that method from f# code.

**Comment by gusty** [comment]
I would say it's weird in general F# naming convention guidelines, which states that functions should start with lowercase and static members with capital, whether if it's a function or a static member is an implementation detail.

**Comment by gusty** [comment]
Yes, they both compile to the same in the end, so from other language they are indeed the same thing.
But even in F# they are just an implementation detail.

I propose to open a suggestion here: https://github.com/cartermp/docs/blob/style/docs/fsharp/style-guide and take this discussion there.

**Comment by wallymathieu** [comment]
I've added a PR https://github.com/cartermp/docs/pull/1
