### ISSUE TITLE
Individual namespaces for each Json distribution

### ISSUE THREAD

**Issue by gusty** [mausch/Fleece#23]
Currently all dlls compile to the same namespace: ``Fleece``.

This means that it would be impossible to use two implementations at the same time (in the same project).

I propose to use different namespaces:

    Fleece.FSharpData
    Fleece.NewtonSoft
    Fleece    // I would keep it for System.Json for now

**Comment by wallymathieu** [comment]
I think it would be nice to have separate namespaces for Fleece implementations. Having same namespace could get into a hurdle if you for some reason need to consume packages that need two different fleeces.

**Comment by gusty** [comment]
Another variation would be to add the ``toJson``, ``ofJson`` generic functions to each json dll existing namespace, I mean, something like:

    open Fleece
    let x = toJson ... // calls default implementation (right now it's System.Json)

    open Newtonsoft.Json
    let y = toJson .. // calls Newtonsoft implementation, shadows previous function

    open FSharp.Data
    let z = toJson .. // calls FSharp.Data implementation, shadows previous function

    let js = Newtonsoft.Json.toJson .. // calls Newtonsoft implementation, without shadowing

What do you think?
Is this the best way to go?
Or creating namespaces under ``Fleece`` as in my first comment?

cc @eulerfx

**Comment by gusty** [comment]
I am thinking now that even for System.Json we should make it in a separate namespace.
Probably this is part of another question: Should we treat System.Json as a default or not?

**Comment by gusty** [comment]
That's certainly a good point.

But I would go further and say that none of them are the default.

We should have no default for the moment, we'll reserve the default for a potential neutral version, if we ever do that.
