### ISSUE TITLE
Switch to Result<_,_> ?

### ISSUE THREAD

**Issue by gusty** [mausch/Fleece#36]
Should we switch to `Result<_,_>` and discard `Choice<_,_>` ?

This will not be a source breaking change since we use an alias, but it will be a binary breaking change, anyway we're still in 0.x so it should be fine.

How about people who's using it in production? @BlythMeister  @harrisonmeister what's your feeling about it?

**Comment by BlythMeister** [comment]
If it's not a binary breaking change, I see no issue with it.

**Comment by gusty** [comment]
It will be a binary breaking change.
It's not a source code breaking, it will keep compiling as long as you use the JsonResult alias in your code, but you might have to recompile your dlls / applications that are referencing Fleece.

Having said that, the other question is do we want to move to Result?

F# seems to be pushing to use Result as the new standard for typed errors, but there's still some libraries that use Choice.

**Comment by gusty** [comment]
@BlythMeister are you guys pinning the Fleece version?

If not I would recommend to do so until we reach a stable version. That will keep you out of problems in the meantime.
