### ISSUE TITLE
F#+ and Fleece ParseResult

### ISSUE THREAD

**Issue by wallymathieu** [mausch/Fleece#43]
Using Fleece together with F#+ can cause some weirdness, mainly due to Failure being both defined in F#+ and Fleece.

**Comment by gusty** [comment]
I would remove Failure from both projects, since now we have `Result.Error` which express intentions.

However F#+ is already stabilized, we'll have to wait until next major release.

We can remove it from Fleece.

**Comment by wallymathieu** [comment]
In f#+ it's part of `Validation`, so it makes more sense to keep it there.
