### ISSUE TITLE
Fleece has no overload for ArraySegment<'a> on jfieldOption

### ISSUE THREAD

**Issue by 7sharp9** [mausch/Fleece#61]
Fleece has no overload for ArraySegment<'a> on jfieldOption, we could edit the generated code in Falanx to emit `array 'a` or add an overload to fleece for ArraySegment<'a>.

See https://github.com/jet/falanx/issues/80

**Comment by gusty** [comment]
I'm happy to add an overload for ArraySegment but the question is how do we expect it to be represented in JSON?

Maybe we could use a structure like `[offset = 1500; array = ["a", "b", "c"]]`

Does it makes sense?

**Comment by 7sharp9** [comment]
In Falnanx we use ArraySegment due to froto where we have a type alias for that primitive:
```
type proto_bytes = ArraySegment<byte>
```

**Comment by 7sharp9** [comment]
I think `bytes` from the parser is handled as a unique primitive as it is can be used to encode another message in proto as its raw byte structure.

**Comment by 7sharp9** [comment]
We could apply the methodology we did with repeated fields and add an expand/flatten for ArraySegment in Falanx:

```
    let expand (x: ArraySegment<Byte> option) = x |> Option.map (fun x -> x.Array)
    let flatten (x: array<Byte> option) = x |> Option.map (fun x -> ArraySegment(x))
```

**Comment by 7sharp9** [comment]
This way we can keep the signatures in the record intact, not sure how hard it is to add ArraySegment to fleece as Im not really familiar with it.

**Comment by 7sharp9** [comment]
I think it would need this definition:

```
    type ToJson with
        static member inline ToJson (x: 'a array, _: ToJson) = JsonEncode.array ToJson.Invoke x
        //Add another overload for ArraySegment calling ToArray on the segment
        static member inline ToJson (x: 'a ArraySegment, _: ToJson) = JsonEncode.array ToJson.Invoke (x.ToArray())
```

**Comment by 7sharp9** [comment]
Completed via #64
