### ISSUE TITLE
No support for enums on Fleece.Newtonsoft.jfieldOpt for enums

### ISSUE THREAD

**Issue by 7sharp9** [mausch/Fleece#65]
See the following issue in Falanx
https://github.com/jet/falanx/issues/131

**Comment by 7sharp9** [comment]
Looks like this is due to no jsonobj method existing on the enum

**Comment by gusty** [comment]
Yes, an enum, like a DU, is not automatically derived.

**Comment by 7sharp9** [comment]
Also enums cant have members so its not possible to add an implementation of `sonObjCodec`

**Comment by 7sharp9** [comment]
So will this be another case expand/flatten?   @gus

**Comment by gus** [comment]
Probably you want a different Gus :)

**Comment by 7sharp9** [comment]
Oops sorry!
I meant @gusty

**Comment by 7sharp9** [comment]
if the flatten/expand thing is used and we assume the enum carries just ints then somethig like this:
```
    let inline flatten (x:int option) =
        x |> Option.map (fun x -> enum x)
        
    let inline expand (o: Option<'a> when 'a : enum<'b>) =
        match o with
        | Some v -> Some(int v)
        | None -> None
```

**Comment by 7sharp9** [comment]
It still requires a fair bit of work in falanx to wrap the types so Im going to tag that as nice to have for now.

**Comment by gusty** [comment]
PR here #67
